/*
Project Details
** Done ** Set up a blank HTML document with the appropriate links to your JavaScript and CSS files.

** Done ** Write the functions that hit the API. You’re going to want functions that can take a location 
and return the weather data for that location. For now, just console.log() the information.

PJU8WEHS4L2P42ZTYH4CS3KUQ

https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/[location]/[date1]/[date2]?key=YOUR_API_KEY

*/

function getWeather(location) {
  fetch(
    `https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/${location}/?key=PJU8WEHS4L2P42ZTYH4CS3KUQ`,
  )
    .then(function (response) {
      return response.json();
    })
    .then(function (response) {
      processWeatherData(response);
    });
}

getWeather("cary");

function processWeatherData(response) {
  const location = response.resolvedAddress;
  const days = response.days;
  console.log("Location: " + location);
  for (let i = 0; i < days.length; i++) {
    console.log(
      days[i].datetime +
        ": tempmax=" +
        days[i].tempmax +
        ", tempmin=" +
        days[i].tempmin,
        ", condition=" +
        days[i].conditions
    );
  }
}

/* Example of a day

{
      "datetime": "2025-12-22",
      "datetimeEpoch": 1766379600,
      "tempmax": 51.2,
      "tempmin": 27.8,
      "temp": 41.2,
      "feelslikemax": 51.2,
      "feelslikemin": 27.8,
      "feelslike": 39.7,
      "dew": 14.3,
      "humidity": 34.9,
      "precip": 0,
      "precipprob": 0,
      "precipcover": 0,
      "preciptype": null,
      "snow": 0,
      "snowdepth": 0,
      "windgust": 16.1,
      "windspeed": 5.6,
      "winddir": 46.6,
      "pressure": 1033.6,
      "cloudcover": 36.6,
      "visibility": 9.9,
      "solarradiation": 111.1,
      "solarenergy": 9.6,
      "uvindex": 5,
      "severerisk": 10,
      "sunrise": "07:22:16",
      "sunriseEpoch": 1766406136,
      "sunset": "17:06:02",
      "sunsetEpoch": 1766441162,
      "moonphase": 0.09,
      "conditions": "Partially cloudy",
      "description": "Partly cloudy throughout the day.",
      "icon": "partly-cloudy-day",
      "stations": [
        "KTTA",
        "KHRJ",
        "F0554",
        "KRDU"
      ],
      "source": "comb",
      "hours": [
        {
          "datetime": "00:00:00",
          "datetimeEpoch": 1766379600,
          "temp": 42.4,
          "feelslike": 40.2,
          "humidity": 27.37,
          "dew": 11,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 10.3,
          "windspeed": 3.8,
          "winddir": 347,
          "pressure": 1031.7,
          "visibility": 9.9,
          "cloudcover": 22.3,
          "solarradiation": 0,
          "solarenergy": 0,
          "uvindex": 0,
          "severerisk": 10,
          "conditions": "Partially cloudy",
          "icon": "partly-cloudy-night",
          "stations": [
            "KTTA",
            "KHRJ",
            "F0554",
            "KRDU"
          ],
          "source": "obs"
        },
        {
          "datetime": "01:00:00",
          "datetimeEpoch": 1766383200,
          "temp": 39.7,
          "feelslike": 36.6,
          "humidity": 30.72,
          "dew": 11.3,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 11.4,
          "windspeed": 4.4,
          "winddir": 9,
          "pressure": 1032,
          "visibility": 9.9,
          "cloudcover": 0,
          "solarradiation": 0,
          "solarenergy": 0,
          "uvindex": 0,
          "severerisk": 10,
          "conditions": "Clear",
          "icon": "clear-night",
          "stations": [
            "KTTA",
            "KHRJ",
            "F0554",
            "KRDU"
          ],
          "source": "obs"
        },
        {
          "datetime": "02:00:00",
          "datetimeEpoch": 1766386800,
          "temp": 37.9,
          "feelslike": 33.6,
          "humidity": 32.66,
          "dew": 11.1,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 8.1,
          "windspeed": 5.5,
          "winddir": 12,
          "pressure": 1032,
          "visibility": 9.9,
          "cloudcover": 0,
          "solarradiation": 0,
          "solarenergy": 0,
          "uvindex": 0,
          "severerisk": 10,
          "conditions": "Clear",
          "icon": "clear-night",
          "stations": [
            "KTTA",
            "KHRJ",
            "F0554",
            "KRDU"
          ],
          "source": "obs"
        },
        {
          "datetime": "03:00:00",
          "datetimeEpoch": 1766390400,
          "temp": 35.7,
          "feelslike": 33.3,
          "humidity": 36.81,
          "dew": 11.8,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 9.2,
          "windspeed": 3.2,
          "winddir": 1,
          "pressure": 1032.6,
          "visibility": 9.9,
          "cloudcover": 0,
          "solarradiation": 0,
          "solarenergy": 0,
          "uvindex": 0,
          "severerisk": 10,
          "conditions": "Clear",
          "icon": "clear-night",
          "stations": [
            "KTTA",
            "KHRJ",
            "F0554",
            "KRDU"
          ],
          "source": "obs"
        },
        {
          "datetime": "04:00:00",
          "datetimeEpoch": 1766394000,
          "temp": 36.3,
          "feelslike": 34,
          "humidity": 34.19,
          "dew": 10.7,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 8.1,
          "windspeed": 3.2,
          "winddir": 19,
          "pressure": 1033,
          "visibility": 9.9,
          "cloudcover": 0,
          "solarradiation": 0,
          "solarenergy": 0,
          "uvindex": 0,
          "severerisk": 10,
          "conditions": "Clear",
          "icon": "clear-night",
          "stations": [
            "KTTA",
            "KHRJ",
            "F0554",
            "KRDU"
          ],
          "source": "obs"
        },
        {
          "datetime": "05:00:00",
          "datetimeEpoch": 1766397600,
          "temp": 34.5,
          "feelslike": 29.6,
          "humidity": 39.59,
          "dew": 12.4,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 8.1,
          "windspeed": 5.5,
          "winddir": 19,
          "pressure": 1033.1,
          "visibility": 9.9,
          "cloudcover": 0,
          "solarradiation": 0,
          "solarenergy": 0,
          "uvindex": 0,
          "severerisk": 10,
          "conditions": "Clear",
          "icon": "clear-night",
          "stations": [
            "KTTA",
            "KHRJ",
            "F0554",
            "KRDU"
          ],
          "source": "obs"
        },
        {
          "datetime": "06:00:00",
          "datetimeEpoch": 1766401200,
          "temp": 34.4,
          "feelslike": 29.5,
          "humidity": 39.64,
          "dew": 12.3,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 6.9,
          "windspeed": 5.4,
          "winddir": 19,
          "pressure": 1033.8,
          "visibility": 9.9,
          "cloudcover": 0,
          "solarradiation": 0,
          "solarenergy": 0,
          "uvindex": 0,
          "severerisk": 10,
          "conditions": "Clear",
          "icon": "clear-night",
          "stations": [
            "KTTA",
            "KHRJ",
            "F0554",
            "KRDU"
          ],
          "source": "obs"
        },
        {
          "datetime": "07:00:00",
          "datetimeEpoch": 1766404800,
          "temp": 30.3,
          "feelslike": 30.3,
          "humidity": 53.9,
          "dew": 15.6,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 6.9,
          "windspeed": 0,
          "winddir": 0,
          "pressure": 1034.8,
          "visibility": 9.9,
          "cloudcover": 0,
          "solarradiation": 0,
          "solarenergy": 0,
          "uvindex": 0,
          "severerisk": 10,
          "conditions": "Clear",
          "icon": "clear-night",
          "stations": [
            "KTTA",
            "KHRJ",
            "F0554",
            "KRDU"
          ],
          "source": "obs"
        },
        {
          "datetime": "08:00:00",
          "datetimeEpoch": 1766408400,
          "temp": 27.8,
          "feelslike": 27.8,
          "humidity": 61.84,
          "dew": 16.4,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 8.1,
          "windspeed": 3,
          "winddir": 18,
          "pressure": 1035.3,
          "visibility": 9.9,
          "cloudcover": 22.3,
          "solarradiation": 3,
          "solarenergy": 0,
          "uvindex": 0,
          "severerisk": 10,
          "conditions": "Partially cloudy",
          "icon": "partly-cloudy-day",
          "stations": [
            "KTTA",
            "KHRJ",
            "F0554",
            "KRDU"
          ],
          "source": "obs"
        },
        {
          "datetime": "09:00:00",
          "datetimeEpoch": 1766412000,
          "temp": 35.8,
          "feelslike": 35.8,
          "humidity": 43.79,
          "dew": 15.9,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 16.1,
          "windspeed": 3,
          "winddir": 0,
          "pressure": 1035.4,
          "visibility": 9.9,
          "cloudcover": 44.5,
          "solarradiation": 63,
          "solarenergy": 0.2,
          "uvindex": 1,
          "severerisk": 10,
          "conditions": "Partially cloudy",
          "icon": "partly-cloudy-day",
          "stations": [
            "KTTA",
            "KHRJ",
            "F0554",
            "KRDU"
          ],
          "source": "obs"
        },
        {
          "datetime": "10:00:00",
          "datetimeEpoch": 1766415600,
          "temp": 40.9,
          "feelslike": 40.9,
          "humidity": 31.97,
          "dew": 13.2,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 15,
          "windspeed": 0.3,
          "winddir": 4,
          "pressure": 1036.1,
          "visibility": 9.9,
          "cloudcover": 22.3,
          "solarradiation": 126,
          "solarenergy": 0.5,
          "uvindex": 1,
          "severerisk": 10,
          "conditions": "Partially cloudy",
          "icon": "partly-cloudy-day",
          "stations": [
            "KTTA",
            "KHRJ",
            "F0554",
            "KRDU"
          ],
          "source": "obs"
        },
        {
          "datetime": "11:00:00",
          "datetimeEpoch": 1766419200,
          "temp": 44.1,
          "feelslike": 41,
          "humidity": 27.03,
          "dew": 12.2,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 10.3,
          "windspeed": 5.4,
          "winddir": 49,
          "pressure": 1036.1,
          "visibility": 9.9,
          "cloudcover": 22.3,
          "solarradiation": 408,
          "solarenergy": 1.5,
          "uvindex": 4,
          "severerisk": 10,
          "conditions": "Partially cloudy",
          "icon": "partly-cloudy-day",
          "stations": [
            "KTTA",
            "KHRJ",
            "F0554",
            "KRDU"
          ],
          "source": "obs"
        },
        {
          "datetime": "12:00:00",
          "datetimeEpoch": 1766422800,
          "temp": 46.2,
          "feelslike": 46.2,
          "humidity": 24.74,
          "dew": 12.1,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 6.9,
          "windspeed": 0.2,
          "winddir": 3,
          "pressure": 1035.5,
          "visibility": 9.9,
          "cloudcover": 22.3,
          "solarradiation": 478,
          "solarenergy": 1.7,
          "uvindex": 5,
          "severerisk": 10,
          "conditions": "Partially cloudy",
          "icon": "partly-cloudy-day",
          "stations": [
            "KTTA",
            "KHRJ",
            "F0554",
            "KRDU"
          ],
          "source": "obs"
        },
        {
          "datetime": "13:00:00",
          "datetimeEpoch": 1766426400,
          "temp": 48.9,
          "feelslike": 48.9,
          "humidity": 23.16,
          "dew": 12.8,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 5.8,
          "windspeed": 0.7,
          "winddir": 6,
          "pressure": 1035,
          "visibility": 9.9,
          "cloudcover": 44.5,
          "solarradiation": 501,
          "solarenergy": 1.8,
          "uvindex": 5,
          "severerisk": 10,
          "conditions": "Partially cloudy",
          "icon": "partly-cloudy-day",
          "stations": [
            "KTTA",
            "KHRJ",
            "F0554",
            "KRDU"
          ],
          "source": "obs"
        },
        {
          "datetime": "14:00:00",
          "datetimeEpoch": 1766430000,
          "temp": 50,
          "feelslike": 50,
          "humidity": 20.05,
          "dew": 10.5,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 5.8,
          "windspeed": 3.6,
          "winddir": 89,
          "pressure": 1033.8,
          "visibility": 9.9,
          "cloudcover": 44.5,
          "solarradiation": 475,
          "solarenergy": 1.7,
          "uvindex": 5,
          "severerisk": 10,
          "conditions": "Partially cloudy",
          "icon": "partly-cloudy-day",
          "stations": [
            "KTTA",
            "KHRJ",
            "F0554",
            "KRDU"
          ],
          "source": "obs"
        },
        {
          "datetime": "15:00:00",
          "datetimeEpoch": 1766433600,
          "temp": 51.2,
          "feelslike": 51.2,
          "humidity": 20.5,
          "dew": 12,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 5.8,
          "windspeed": 5.6,
          "winddir": 110,
          "pressure": 1033,
          "visibility": 9.9,
          "cloudcover": 44.5,
          "solarradiation": 352,
          "solarenergy": 1.3,
          "uvindex": 4,
          "severerisk": 10,
          "conditions": "Partially cloudy",
          "icon": "partly-cloudy-day",
          "stations": [
            "KTTA",
            "KHRJ",
            "F0554",
            "KRDU"
          ],
          "source": "obs"
        },
        {
          "datetime": "16:00:00",
          "datetimeEpoch": 1766437200,
          "temp": 51.2,
          "feelslike": 51.2,
          "humidity": 21.27,
          "dew": 12.8,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 5.8,
          "windspeed": 4.3,
          "winddir": 28,
          "pressure": 1033.2,
          "visibility": 9.9,
          "cloudcover": 44.5,
          "solarradiation": 232,
          "solarenergy": 0.8,
          "uvindex": 2,
          "severerisk": 10,
          "conditions": "Partially cloudy",
          "icon": "partly-cloudy-day",
          "stations": [
            "KTTA",
            "KHRJ",
            "F0554",
            "KRDU"
          ],
          "source": "obs"
        },
        {
          "datetime": "17:00:00",
          "datetimeEpoch": 1766440800,
          "temp": 48.5,
          "feelslike": 47.9,
          "humidity": 24.16,
          "dew": 13.5,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 6.9,
          "windspeed": 3.1,
          "winddir": 147,
          "pressure": 1033.2,
          "visibility": 9.9,
          "cloudcover": 78.4,
          "solarradiation": 29,
          "solarenergy": 0.1,
          "uvindex": 0,
          "severerisk": 10,
          "conditions": "Partially cloudy",
          "icon": "partly-cloudy-day",
          "stations": [
            "KTTA",
            "KHRJ",
            "F0554",
            "KRDU"
          ],
          "source": "obs"
        },
        {
          "datetime": "18:00:00",
          "datetimeEpoch": 1766444400,
          "temp": 46.5,
          "feelslike": 46.5,
          "humidity": 31.41,
          "dew": 17.7,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 4.7,
          "windspeed": 3,
          "winddir": 116,
          "pressure": 1033.3,
          "visibility": 9.9,
          "cloudcover": 78.4,
          "solarradiation": 0,
          "solarenergy": 0,
          "uvindex": 0,
          "severerisk": 10,
          "conditions": "Partially cloudy",
          "icon": "partly-cloudy-night",
          "stations": [
            "KTTA",
            "KHRJ",
            "F0554",
            "KRDU"
          ],
          "source": "obs"
        },
        {
          "datetime": "19:00:00",
          "datetimeEpoch": 1766448000,
          "temp": 44.3,
          "feelslike": 41.3,
          "humidity": 34.74,
          "dew": 18.2,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 4.7,
          "windspeed": 5.3,
          "winddir": 31,
          "pressure": 1033.2,
          "visibility": 9.9,
          "cloudcover": 89.1,
          "solarradiation": 0,
          "solarenergy": 0,
          "uvindex": 0,
          "severerisk": 10,
          "conditions": "Partially cloudy",
          "icon": "partly-cloudy-night",
          "stations": [
            "KTTA",
            "KHRJ",
            "F0554",
            "KRDU"
          ],
          "source": "obs"
        },
        {
          "datetime": "20:00:00",
          "datetimeEpoch": 1766451600,
          "temp": 44.2,
          "feelslike": 42,
          "humidity": 33.44,
          "dew": 17.2,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 4.7,
          "windspeed": 4.2,
          "winddir": 151,
          "pressure": 1033,
          "visibility": 9.9,
          "cloudcover": 89.1,
          "solarradiation": 0,
          "solarenergy": 0,
          "uvindex": 0,
          "severerisk": 10,
          "conditions": "Partially cloudy",
          "icon": "partly-cloudy-night",
          "stations": [
            "KTTA",
            "KHRJ",
            "F0554",
            "KRDU"
          ],
          "source": "obs"
        },
        {
          "datetime": "21:00:00",
          "datetimeEpoch": 1766455200,
          "temp": 43.2,
          "feelslike": 40.9,
          "humidity": 34.59,
          "dew": 17.1,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 4.7,
          "windspeed": 4.2,
          "winddir": 160,
          "pressure": 1033.1,
          "visibility": 9.9,
          "cloudcover": 89.1,
          "solarradiation": 0,
          "solarenergy": 0,
          "uvindex": 0,
          "severerisk": 10,
          "conditions": "Partially cloudy",
          "icon": "partly-cloudy-night",
          "stations": [
            "KTTA",
            "KHRJ",
            "F0554",
            "KRDU"
          ],
          "source": "obs"
        },
        {
          "datetime": "22:00:00",
          "datetimeEpoch": 1766458800,
          "temp": 36.9,
          "feelslike": 36.9,
          "humidity": 54.39,
          "dew": 22,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 4.7,
          "windspeed": 2.2,
          "winddir": 170,
          "pressure": 1032,
          "visibility": 10.1,
          "cloudcover": 63,
          "solarradiation": 0,
          "solarenergy": 0,
          "uvindex": 0,
          "severerisk": 10,
          "conditions": "Partially cloudy",
          "icon": "partly-cloudy-night",
          "stations": null,
          "source": "fcst"
        },
        {
          "datetime": "23:00:00",
          "datetimeEpoch": 1766462400,
          "temp": 36.9,
          "feelslike": 36.9,
          "humidity": 56.49,
          "dew": 22.9,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 4.7,
          "windspeed": 2.2,
          "winddir": 170,
          "pressure": 1032,
          "visibility": 10.1,
          "cloudcover": 58,
          "solarradiation": 0,
          "solarenergy": 0,
          "uvindex": 0,
          "severerisk": 10,
          "conditions": "Partially cloudy",
          "icon": "partly-cloudy-night",
          "stations": null,
          "source": "fcst"
        }
      ]
    }

*/

/*
Write the functions that process the JSON data you’re getting from the API and return an object 
with only the data you require for your app.

Set up a form that will let users input their location and will fetch the weather info (still just console.log() it).

Display the information on your webpage!

While you don’t have to, if you wish to display weather icons then there can be a lot of them to import, 
so have a look at the dynamic import() function. Unlike plain template strings without an import, 
Webpack can read dynamic imports and still bundle all the relevant assets.

Add any styling you like!

Optional: add a ‘loading’ component that displays from the time the form is submitted until the information 
comes back from the API. Use DevTools to simulate network speeds.

Push that baby to GitHub and share your solution below!
*/
